
name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.5"
      - name: Install coverage
        run: pip install pytest coverage
      - name: Run tests
        run: coverage run -m pytest Board.py
        # run: coverage run -m pytest AI.py
        # run: coverage run -m pytest pbrain-gomoku-ai.py
        # run: coverage run -m pytest input_parser.py
